using System.Globalization;
using System.Text;

namespace ZeroAlloc.Jev.Generator;

/// <summary>Writes the C# source for one question set.</summary>
internal static class SourceEmitter
{
    private const string Reader = "global::ZeroAlloc.Jev.JevAnswerReader";

    public static string HintName(QuestionSetModel model)
        => ((model.Namespace is null ? string.Empty : model.Namespace + ".") + model.TypeName + ".JevQuestions.g.cs")
            .Replace("@", string.Empty);

    public static string Emit(QuestionSetModel model)
    {
        var code = new CodeWriter();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line();
        if (model.Namespace is not null)
        {
            code.Line("namespace " + model.Namespace + ";");
            code.Line();
        }

        code.Line("partial " + (model.IsRecord ? "record " : "class ") + model.TypeName
            + " : global::ZeroAlloc.Jev.IJevQuestionSet<" + model.FullyQualifiedName + ">");
        code.Line("{");

        foreach (var question in model.Questions)
        {
            code.Line("    private " + PropertyType(question) + " " + Field(question) + ";");
        }

        code.Line();
        foreach (var question in model.Questions)
        {
            var modifiers = question.Modifiers.Length == 0 ? string.Empty : question.Modifiers + " ";
            code.Line("    " + modifiers + "partial " + PropertyType(question) + " " + question.PropertyName
                + " { get => " + Field(question) + "; }");
        }

        code.Line();
        code.Line("    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>");
        code.Line("    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "
            + JsonText.CSharpLiteral(QuestionsJson(model)) + "u8;");
        code.Line();
        EmitParse(code, model);

        foreach (var question in model.Questions)
        {
            if (question.Kind != QuestionKind.Noul)
            {
                code.Line();
                EmitOptionSet(code, question);
            }
        }

        code.Line("}");
        return code.ToString();
    }

    private static void EmitParse(CodeWriter code, QuestionSetModel model)
    {
        var bufferLength = model.Questions.Sum(question => question.Options.Length);
        var needsBuffer = model.Questions.Any(question => question.Kind != QuestionKind.Noul);

        code.Line("    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>");
        code.Line("    /// <param name=\"answers\">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>");
        code.Line("    /// <returns>The typed answers.</returns>");
        code.Line("    public static " + model.FullyQualifiedName + " Parse(ref global::System.Text.Json.Utf8JsonReader answers)");
        code.Line("    {");
        code.Line("        " + Reader + ".EnsureStartObject(ref answers);");
        if (needsBuffer)
        {
            code.Line("        var buffer = " + (bufferLength > 0
                ? "new double[" + Int(bufferLength) + "];"
                : "global::System.Array.Empty<double>();"));
        }

        code.Line("        var result = new " + model.FullyQualifiedName + "();");
        for (var i = 0; i < model.Questions.Length; i++)
        {
            code.Line("        var found" + Int(i) + " = false;");
        }

        code.Line("        while (" + Reader + ".NextProperty(ref answers))");
        code.Line("        {");

        var offset = 0;
        for (var i = 0; i < model.Questions.Length; i++)
        {
            var question = model.Questions[i];
            var call = question.Kind switch
            {
                QuestionKind.Noul => Reader + ".ReadNoul(ref answers)",
                QuestionKind.Choice => Reader + ".ReadChoice(ref answers, " + OptionSet(question) + ".Instance, buffer, " + Int(offset) + ")",
                _ => Reader + ".ReadScore(ref answers, " + OptionSet(question) + ".Instance, buffer, " + Int(offset) + ")",
            };

            code.Line("            " + (i == 0 ? "if" : "else if") + " (answers.ValueTextEquals(" + JsonText.CSharpLiteral(question.Key) + "u8))");
            code.Line("            {");
            code.Line("                answers.Read();");
            code.Line("                result." + Field(question) + " = " + call + ";");
            code.Line("                found" + Int(i) + " = true;");
            code.Line("            }");
            offset += question.Options.Length;
        }

        if (model.Questions.Length == 0)
        {
            code.Line("            answers.Skip();");
        }
        else
        {
            code.Line("            else");
            code.Line("            {");
            code.Line("                answers.Skip();");
            code.Line("            }");
        }

        code.Line("        }");
        for (var i = 0; i < model.Questions.Length; i++)
        {
            code.Line("        if (!found" + Int(i) + ") throw " + Reader + ".MissingAnswer("
                + JsonText.CSharpLiteral(model.Questions[i].Key) + ");");
        }

        code.Line("        return result;");
        code.Line("    }");
    }

    private static void EmitOptionSet(CodeWriter code, QuestionModel question)
    {
        var name = OptionSet(question);
        var enumType = question.EnumType;

        code.Line("    private sealed class " + name + " : global::ZeroAlloc.Jev.JevOptionSet<" + enumType + ">");
        code.Line("    {");
        code.Line("        public static readonly " + name + " Instance = new();");
        code.Line();
        code.Line("        public override int Count => " + Int(question.Options.Length) + ";");
        code.Line();
        code.Line("        public override " + enumType + " this[int index] => index switch");
        code.Line("        {");
        for (var i = 0; i < question.Options.Length; i++)
        {
            code.Line("            " + Int(i) + " => " + enumType + "." + question.Options[i].MemberName + ",");
        }

        code.Line("            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),");
        code.Line("        };");
        code.Line();
        code.Line("        public override int IndexOf(" + enumType + " value) => value switch");
        code.Line("        {");
        for (var i = 0; i < question.Options.Length; i++)
        {
            code.Line("            " + enumType + "." + question.Options[i].MemberName + " => " + Int(i) + ",");
        }

        code.Line("            _ => -1,");
        code.Line("        };");
        code.Line();
        code.Line("        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)");
        code.Line("        {");
        for (var i = 0; i < question.Options.Length; i++)
        {
            code.Line("            if (reader.ValueTextEquals(" + JsonText.CSharpLiteral(question.Options[i].Key) + "u8)) return " + Int(i) + ";");
        }

        code.Line("            return -1;");
        code.Line("        }");
        code.Line("    }");
    }

    private static string QuestionsJson(QuestionSetModel model)
    {
        var json = new StringBuilder().Append('{');
        for (var i = 0; i < model.Questions.Length; i++)
        {
            var question = model.Questions[i];
            if (i > 0)
            {
                json.Append(',');
            }

            json.AppendJsonString(question.Key).Append(":{\"type\":");
            json.AppendJsonString(question.Kind switch
            {
                QuestionKind.Noul => "noul",
                QuestionKind.Choice => "choice",
                _ => "score",
            });
            json.Append(",\"instructions\":").AppendJsonString(question.Instructions);

            switch (question.Kind)
            {
                case QuestionKind.Noul when question.WhenTrue is not null || question.WhenFalse is not null:
                    json.Append(",\"criteria\":{");
                    if (question.WhenTrue is not null)
                    {
                        json.Append("\"true\":").AppendJsonString(question.WhenTrue);
                    }

                    if (question.WhenFalse is not null)
                    {
                        json.Append(question.WhenTrue is null ? "\"false\":" : ",\"false\":").AppendJsonString(question.WhenFalse);
                    }

                    json.Append('}');
                    break;

                case QuestionKind.Choice:
                    json.Append(",\"criteria\":{");
                    for (var j = 0; j < question.Options.Length; j++)
                    {
                        var option = question.Options[j];
                        if (j > 0)
                        {
                            json.Append(',');
                        }

                        json.AppendJsonString(option.Key).Append(':');
                        if (option.Description is null)
                        {
                            json.Append("null");
                        }
                        else
                        {
                            json.AppendJsonString(option.Description);
                        }
                    }

                    json.Append('}');
                    break;

                case QuestionKind.Score:
                    json.Append(",\"criteria\":[");
                    for (var j = 0; j < question.Options.Length; j++)
                    {
                        if (j > 0)
                        {
                            json.Append(',');
                        }

                        json.AppendJsonString(question.Options[j].Description ?? string.Empty);
                    }

                    json.Append(']');
                    break;
            }

            json.Append('}');
        }

        return json.Append('}').ToString();
    }

    private static string PropertyType(QuestionModel question) => question.Kind switch
    {
        QuestionKind.Noul => "global::ZeroAlloc.Jev.Noul",
        QuestionKind.Choice => "global::ZeroAlloc.Jev.Choice<" + question.EnumType + ">",
        _ => "global::ZeroAlloc.Jev.Score<" + question.EnumType + ">",
    };

    private static string Field(QuestionModel question) => "__jev_" + question.PropertyName.TrimStart('@');

    private static string OptionSet(QuestionModel question) => "__JevOptions_" + question.PropertyName.TrimStart('@');

    private static string Int(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>Appends lines with <c>\n</c> endings so the output does not depend on the build machine.</summary>
    private sealed class CodeWriter
    {
        private readonly StringBuilder _text = new();

        public void Line(string text = "") => _text.Append(text).Append('\n');

        public override string ToString() => _text.ToString();
    }
}
