import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One sidebar generated from docs/: pages sort by their front-matter sidebar_position, and docs/patterns/ by the
// position in its _category_.json. The README's Documentation list follows the same order, and ReadmeLinkTests
// checks it, so a page added here in the wrong place fails a test rather than drifting.
const sidebars: SidebarsConfig = {
  guideSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
