//HintName: Demo.JsonRouting.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record JsonRouting : global::ZeroAlloc.Jev.IJevQuestionSet<global::Demo.JsonRouting>
{
    private global::ZeroAlloc.Jev.Noul __jev_IsUrgent;
    private global::ZeroAlloc.Jev.Choice<global::Demo.JsonDepartment> __jev_Department;

    public partial global::ZeroAlloc.Jev.Noul IsUrgent { get => __jev_IsUrgent; }
    public partial global::ZeroAlloc.Jev.Choice<global::Demo.JsonDepartment> Department { get => __jev_Department; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"is_urgent\":{\"type\":\"noul\",\"instructions\":{\"question\":\"Is this urgent?\",\"hints\":[\"deadline\",\"outage\"]}},\"department\":{\"type\":\"choice\",\"instructions\":[\"Which team should handle this?\"],\"criteria\":{\"billing\":{\"description\":\"a\",\"examples\":[\"\\u00e9\"]},\"technical\":\"Bugs, outages, integrations\"}}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.JsonRouting Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::ZeroAlloc.Jev.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[2];
        var result = new global::Demo.JsonRouting();
        var found0 = false;
        var found1 = false;
        while (global::ZeroAlloc.Jev.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("is_urgent"u8))
            {
                answers.Read();
                result.__jev_IsUrgent = global::ZeroAlloc.Jev.JevAnswerReader.ReadNoul(ref answers);
                found0 = true;
            }
            else if (answers.ValueTextEquals("department"u8))
            {
                answers.Read();
                result.__jev_Department = global::ZeroAlloc.Jev.JevAnswerReader.ReadChoice(ref answers, __JevOptions_Department.Instance, buffer, 0);
                found1 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("is_urgent");
        if (!found1) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("department");
        return result;
    }

    private sealed class __JevOptions_Department : global::ZeroAlloc.Jev.JevOptionSet<global::Demo.JsonDepartment>
    {
        public static readonly __JevOptions_Department Instance = new();

        public override int Count => 2;

        public override global::Demo.JsonDepartment this[int index] => index switch
        {
            0 => global::Demo.JsonDepartment.Billing,
            1 => global::Demo.JsonDepartment.Technical,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.JsonDepartment value) => value switch
        {
            global::Demo.JsonDepartment.Billing => 0,
            global::Demo.JsonDepartment.Technical => 1,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("billing"u8)) return 0;
            if (reader.ValueTextEquals("technical"u8)) return 1;
            return -1;
        }
    }
}
