//HintName: Demo.FrustrationCheck.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record FrustrationCheck : global::ZeroAlloc.Jev.IJevQuestionSet<global::Demo.FrustrationCheck>
{
    private global::ZeroAlloc.Jev.Score<global::Demo.Frustration> __jev_Frustration;

    public partial global::ZeroAlloc.Jev.Score<global::Demo.Frustration> Frustration { get => __jev_Frustration; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"frustration\":{\"type\":\"score\",\"instructions\":\"How frustrated is the customer?\",\"criteria\":[\"Calm\",\"Frustrated\",\"Very angry\"]}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.FrustrationCheck Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::ZeroAlloc.Jev.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[3];
        var result = new global::Demo.FrustrationCheck();
        var found0 = false;
        while (global::ZeroAlloc.Jev.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("frustration"u8))
            {
                answers.Read();
                result.__jev_Frustration = global::ZeroAlloc.Jev.JevAnswerReader.ReadScore(ref answers, __JevOptions_Frustration.Instance, buffer, 0);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("frustration");
        return result;
    }

    private sealed class __JevOptions_Frustration : global::ZeroAlloc.Jev.JevOptionSet<global::Demo.Frustration>
    {
        public static readonly __JevOptions_Frustration Instance = new();

        public override int Count => 3;

        public override global::Demo.Frustration this[int index] => index switch
        {
            0 => global::Demo.Frustration.Calm,
            1 => global::Demo.Frustration.Frustrated,
            2 => global::Demo.Frustration.VeryAngry,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Frustration value) => value switch
        {
            global::Demo.Frustration.Calm => 0,
            global::Demo.Frustration.Frustrated => 1,
            global::Demo.Frustration.VeryAngry => 2,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("0"u8)) return 0;
            if (reader.ValueTextEquals("1"u8)) return 1;
            if (reader.ValueTextEquals("2"u8)) return 2;
            return -1;
        }
    }
}
