//HintName: Demo.StructuredRouting.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record StructuredRouting : global::ZeroAlloc.Jev.IJevQuestionSet<global::Demo.StructuredRouting>
{
    private global::ZeroAlloc.Jev.Choice<global::Demo.StructuredDepartment> __jev_Department;
    private global::ZeroAlloc.Jev.Score<global::Demo.StructuredSeverity> __jev_Severity;

    public partial global::ZeroAlloc.Jev.Choice<global::Demo.StructuredDepartment> Department { get => __jev_Department; }
    public partial global::ZeroAlloc.Jev.Score<global::Demo.StructuredSeverity> Severity { get => __jev_Severity; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"department\":{\"type\":\"choice\",\"instructions\":\"Which team should handle this?\",\"criteria\":{\"billing\":{\"description\":\"Payments, invoicing, refunds\",\"examples\":[\"I was charged twice\"],\"not_for\":[\"How much is Pro?\"]},\"technical\":{\"description\":\"Bugs, outages, integrations\",\"examples\":[\"The API returns 500\"]},\"sales\":\"Pricing, upgrades, new accounts\",\"other\":null}},\"severity\":{\"type\":\"score\",\"instructions\":\"How severe is this?\",\"criteria\":[{\"description\":\"Cosmetic\",\"not_for\":[\"Data loss\"]},\"Blocks work\"]}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.StructuredRouting Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::ZeroAlloc.Jev.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[6];
        var result = new global::Demo.StructuredRouting();
        var found0 = false;
        var found1 = false;
        while (global::ZeroAlloc.Jev.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("department"u8))
            {
                answers.Read();
                result.__jev_Department = global::ZeroAlloc.Jev.JevAnswerReader.ReadChoice(ref answers, __JevOptions_Department.Instance, buffer, 0);
                found0 = true;
            }
            else if (answers.ValueTextEquals("severity"u8))
            {
                answers.Read();
                result.__jev_Severity = global::ZeroAlloc.Jev.JevAnswerReader.ReadScore(ref answers, __JevOptions_Severity.Instance, buffer, 4);
                found1 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("department");
        if (!found1) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("severity");
        return result;
    }

    private sealed class __JevOptions_Department : global::ZeroAlloc.Jev.JevOptionSet<global::Demo.StructuredDepartment>
    {
        public static readonly __JevOptions_Department Instance = new();

        public override int Count => 4;

        public override global::Demo.StructuredDepartment this[int index] => index switch
        {
            0 => global::Demo.StructuredDepartment.Billing,
            1 => global::Demo.StructuredDepartment.Technical,
            2 => global::Demo.StructuredDepartment.Sales,
            3 => global::Demo.StructuredDepartment.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredDepartment value) => value switch
        {
            global::Demo.StructuredDepartment.Billing => 0,
            global::Demo.StructuredDepartment.Technical => 1,
            global::Demo.StructuredDepartment.Sales => 2,
            global::Demo.StructuredDepartment.Other => 3,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("billing"u8)) return 0;
            if (reader.ValueTextEquals("technical"u8)) return 1;
            if (reader.ValueTextEquals("sales"u8)) return 2;
            if (reader.ValueTextEquals("other"u8)) return 3;
            return -1;
        }
    }

    private sealed class __JevOptions_Severity : global::ZeroAlloc.Jev.JevOptionSet<global::Demo.StructuredSeverity>
    {
        public static readonly __JevOptions_Severity Instance = new();

        public override int Count => 2;

        public override global::Demo.StructuredSeverity this[int index] => index switch
        {
            0 => global::Demo.StructuredSeverity.Low,
            1 => global::Demo.StructuredSeverity.High,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredSeverity value) => value switch
        {
            global::Demo.StructuredSeverity.Low => 0,
            global::Demo.StructuredSeverity.High => 1,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("0"u8)) return 0;
            if (reader.ValueTextEquals("1"u8)) return 1;
            return -1;
        }
    }
}
