//HintName: TicketTriage.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

partial class TicketTriage : global::ZeroAlloc.Jev.IJevQuestionSet<global::TicketTriage>
{
    private global::ZeroAlloc.Jev.Noul __jev_RequestsCredentials;
    private global::ZeroAlloc.Jev.Choice<global::Team> __jev_Team;
    private global::ZeroAlloc.Jev.Score<global::Urgency> __jev_Urgency;

    public partial global::ZeroAlloc.Jev.Noul RequestsCredentials { get => __jev_RequestsCredentials; }
    public partial global::ZeroAlloc.Jev.Choice<global::Team> Team { get => __jev_Team; }
    internal partial global::ZeroAlloc.Jev.Score<global::Urgency> Urgency { get => __jev_Urgency; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"requests_credentials\":{\"type\":\"noul\",\"instructions\":\"Does `message` ask for a \\\"credential\\\"?\",\"criteria\":{\"false\":\"No credential is requested\"}},\"route_to\":{\"type\":\"choice\",\"instructions\":\"Which team should handle `message`?\",\"criteria\":{\"billing\":\"Charges, invoices, refunds\",\"account\":\"Login, profile, permissions, or security\",\"other\":\"No listed team fits\"}},\"urgency\":{\"type\":\"score\",\"instructions\":\"How urgent is `message`?\",\"criteria\":[\"Can wait\",\"This week\",\"Today\"]}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::TicketTriage Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::ZeroAlloc.Jev.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[6];
        var result = new global::TicketTriage();
        var found0 = false;
        var found1 = false;
        var found2 = false;
        while (global::ZeroAlloc.Jev.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("requests_credentials"u8))
            {
                answers.Read();
                result.__jev_RequestsCredentials = global::ZeroAlloc.Jev.JevAnswerReader.ReadNoul(ref answers);
                found0 = true;
            }
            else if (answers.ValueTextEquals("route_to"u8))
            {
                answers.Read();
                result.__jev_Team = global::ZeroAlloc.Jev.JevAnswerReader.ReadChoice(ref answers, __JevOptions_Team.Instance, buffer, 0);
                found1 = true;
            }
            else if (answers.ValueTextEquals("urgency"u8))
            {
                answers.Read();
                result.__jev_Urgency = global::ZeroAlloc.Jev.JevAnswerReader.ReadScore(ref answers, __JevOptions_Urgency.Instance, buffer, 3);
                found2 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("requests_credentials");
        if (!found1) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("route_to");
        if (!found2) throw global::ZeroAlloc.Jev.JevAnswerReader.MissingAnswer("urgency");
        return result;
    }

    private sealed class __JevOptions_Team : global::ZeroAlloc.Jev.JevOptionSet<global::Team>
    {
        public static readonly __JevOptions_Team Instance = new();

        public override int Count => 3;

        public override global::Team this[int index] => index switch
        {
            0 => global::Team.Billing,
            1 => global::Team.Account,
            2 => global::Team.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Team value) => value switch
        {
            global::Team.Billing => 0,
            global::Team.Account => 1,
            global::Team.Other => 2,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("billing"u8)) return 0;
            if (reader.ValueTextEquals("account"u8)) return 1;
            if (reader.ValueTextEquals("other"u8)) return 2;
            return -1;
        }
    }

    private sealed class __JevOptions_Urgency : global::ZeroAlloc.Jev.JevOptionSet<global::Urgency>
    {
        public static readonly __JevOptions_Urgency Instance = new();

        public override int Count => 3;

        public override global::Urgency this[int index] => index switch
        {
            0 => global::Urgency.Low,
            1 => global::Urgency.Medium,
            2 => global::Urgency.High,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Urgency value) => value switch
        {
            global::Urgency.Low => 0,
            global::Urgency.Medium => 1,
            global::Urgency.High => 2,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("0"u8)) return 0;
            if (reader.ValueTextEquals("1"u8)) return 1;
            if (reader.ValueTextEquals("2"u8)) return 2;
            return -1;
        }
    }
}
