using System.Globalization;
using System.Text;

namespace Minos.Generator;

/// <summary>Writes the C# source for one question set.</summary>
internal static class SourceEmitter
{
    // The whole message is a string literal the stub getters throw; MIN errors keep the stubs from ever running.
    private const string InvalidSetMessage = "\"This [Questions] set is invalid; see the MIN diagnostics.\"";

    public static string HintName(QuestionSetModel model) => HintName(model.Namespace, model.TypeName);

    /// <summary>
    /// The hint name of a set's stubs: its containing types and its own name, each with its arity when generic, so a
    /// nested or generic set cannot clash with another of the same name. A top-level non-generic set gets the name a
    /// valid one would.
    /// </summary>
    public static string HintName(InvalidSetModel model)
        => HintName(model.Namespace, string.Join(".", model.ContainingTypes.Append(model.Type).Select(type =>
            type.Arity == 0 ? type.Name : type.Name + "`" + type.Arity.ToString(CultureInfo.InvariantCulture))));

    /// <summary>
    /// Implements an invalid set's partial question properties with accessors that throw, and nothing else: no
    /// <c>Definition</c>, no <c>Create</c> and no <c>IQuestionSet</c>. Without them, each property would be
    /// CS9248, a declaration error that stops a command-line build before the analyzer reports the MIN error.
    /// </summary>
    public static string EmitStubs(InvalidSetModel model)
    {
        var code = new CodeWriter();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line();
        if (model.Namespace is not null)
        {
            code.Line("namespace " + model.Namespace + ";");
            code.Line();
        }

        // The containing types, outermost first, then the set, each one level deeper.
        var types = model.ContainingTypes.Append(model.Type).ToList();
        for (var depth = 0; depth < types.Count; depth++)
        {
            var type = types[depth];
            var indent = Indent(depth);
            code.Line(indent + (type.Modifiers.Length == 0 ? string.Empty : type.Modifiers + " ")
                + "partial " + type.Keyword + " " + type.Name + type.TypeParameters);
            code.Line(indent + "{");
        }

        var memberIndent = Indent(types.Count);
        foreach (var property in model.Properties)
        {
            var accessors = string.Concat(property.Accessors.Select(accessor =>
                " " + (accessor.Modifiers.Length == 0 ? string.Empty : accessor.Modifiers + " ") + accessor.Keyword
                + " => throw new global::System.InvalidOperationException(" + InvalidSetMessage + ");"));
            code.Line(memberIndent + property.Modifiers + " " + property.TypeName + " " + property.PropertyName + " {" + accessors + " }");
        }

        for (var depth = types.Count - 1; depth >= 0; depth--)
        {
            code.Line(Indent(depth) + "}");
        }

        return code.ToString();
    }

    private static string Indent(int depth) => new(' ', depth * 4);

    private static string HintName(string? ns, string typeName)
        => ((ns is null ? string.Empty : ns + ".") + typeName + ".Questions.g.cs").Replace("@", string.Empty);

    public static string Emit(QuestionSetModel model)
    {
        var code = new CodeWriter();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line();
        if (model.Namespace is not null)
        {
            code.Line("namespace " + model.Namespace + ";");
            code.Line();
        }

        var stateArgument = model.StateTypeName is null ? string.Empty : ", " + model.StateTypeName;
        code.Line("partial " + (model.IsRecord ? "record " : "class ") + model.TypeName
            + " : global::Minos.IQuestionSet<" + model.FullyQualifiedName + stateArgument + ">");
        code.Line("{");

        foreach (var question in model.Questions)
        {
            code.Line("    private " + PropertyType(question) + " " + Field(question) + ";");
        }

        code.Line();
        foreach (var question in model.Questions)
        {
            var modifiers = question.Modifiers.Length == 0 ? string.Empty : question.Modifiers + " ";
            code.Line("    " + modifiers + "partial " + PropertyType(question) + " " + question.PropertyName
                + " { get => " + Field(question) + "; }");
        }

        code.Line();
        EmitDefinition(code, model);
        code.Line();
        EmitCreate(code, model);

        foreach (var question in model.Questions)
        {
            if (question.Kind != QuestionKind.Noul)
            {
                code.Line();
                EmitOptionSet(code, question);
            }
        }

        code.Line("}");
        return code.ToString();
    }

    private static void EmitDefinition(CodeWriter code, QuestionSetModel model)
    {
        code.Line("    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>");
        const string Declaration = "    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(";
        if (model.Questions.Length == 0)
        {
            code.Line(Declaration + ");");
            return;
        }

        code.Line(Declaration);
        for (var i = 0; i < model.Questions.Length; i++)
        {
            var question = model.Questions[i];
            var arguments = new List<string>
            {
                JsonText.CSharpLiteral(question.Key),
                Content(question.Instructions),
            };

            switch (question.Kind)
            {
                case QuestionKind.Noul:
                    if (question.WhenTrue is not null)
                    {
                        arguments.Add("whenTrue: " + Content(question.WhenTrue));
                    }

                    if (question.WhenFalse is not null)
                    {
                        arguments.Add("whenFalse: " + Content(question.WhenFalse));
                    }

                    break;

                case QuestionKind.Choice:
                    arguments.AddRange(question.Options.Select(option => "new global::Minos.OptionDefinition("
                        + JsonText.CSharpLiteral(option.Key) + ", "
                        + (option.Description is null ? "null" : Criterion(option)) + ")"));
                    break;

                default:
                    arguments.AddRange(question.Options.Select(Criterion));
                    break;
            }

            var factory = question.Kind switch
            {
                QuestionKind.Noul => "Noul",
                QuestionKind.Choice => "Choice",
                _ => "Score",
            };

            code.Line("        global::Minos.QuestionDefinition." + factory + "(");
            for (var j = 0; j < arguments.Count; j++)
            {
                var last = j == arguments.Count - 1;
                code.Line("            " + arguments[j] + (!last ? "," : i == model.Questions.Length - 1 ? "));" : "),"));
            }
        }

        static string Content(string text) => "global::Minos.DecisionContent.FromString(" + JsonText.CSharpLiteral(text) + ")";

        static string Criterion(OptionModel option)
        {
            var criterion = "global::Minos.Criterion.Text(" + JsonText.CSharpLiteral(option.Description ?? string.Empty) + ")";
            if (option.Examples.Length > 0)
            {
                criterion += ".WithExamples(" + string.Join(", ", option.Examples.Select(JsonText.CSharpLiteral)) + ")";
            }

            if (option.NotFor.Length > 0)
            {
                criterion += ".WithNotFor(" + string.Join(", ", option.NotFor.Select(JsonText.CSharpLiteral)) + ")";
            }

            return criterion;
        }
    }

    private static void EmitCreate(CodeWriter code, QuestionSetModel model)
    {
        code.Line("    /// <summary>Creates the typed answers from the slots a protocol read for <see cref=\"Definition\"/>.</summary>");
        code.Line("    /// <param name=\"answers\">One slot per question, in <see cref=\"Definition\"/> order.</param>");
        code.Line("    /// <returns>The typed answers.</returns>");
        code.Line("    public static " + model.FullyQualifiedName + " Create(global::Minos.AnswerSlots answers)");
        code.Line("    {");
        code.Line("        var result = new " + model.FullyQualifiedName + "();");
        for (var i = 0; i < model.Questions.Length; i++)
        {
            var question = model.Questions[i];
            var read = question.Kind switch
            {
                QuestionKind.Noul => "answers.Noul(" + Int(i) + ")",
                QuestionKind.Choice => "answers.Choice(" + Int(i) + ", " + OptionSet(question) + ".Instance)",
                _ => "answers.Score(" + Int(i) + ", " + OptionSet(question) + ".Instance)",
            };

            code.Line("        result." + Field(question) + " = " + read + ";");
        }

        code.Line("        return result;");
        code.Line("    }");
    }

    private static void EmitOptionSet(CodeWriter code, QuestionModel question)
    {
        var name = OptionSet(question);
        var enumType = question.EnumType;

        code.Line("    private sealed class " + name + " : global::Minos.DecisionOptionSet<" + enumType + ">");
        code.Line("    {");
        code.Line("        public static readonly " + name + " Instance = new();");
        code.Line();
        code.Line("        public override int Count => " + Int(question.Options.Length) + ";");
        code.Line();
        code.Line("        public override " + enumType + " this[int index] => index switch");
        code.Line("        {");
        for (var i = 0; i < question.Options.Length; i++)
        {
            code.Line("            " + Int(i) + " => " + enumType + "." + question.Options[i].MemberName + ",");
        }

        code.Line("            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),");
        code.Line("        };");
        code.Line();
        code.Line("        public override int IndexOf(" + enumType + " value) => value switch");
        code.Line("        {");
        for (var i = 0; i < question.Options.Length; i++)
        {
            code.Line("            " + enumType + "." + question.Options[i].MemberName + " => " + Int(i) + ",");
        }

        code.Line("            _ => -1,");
        code.Line("        };");
        code.Line("    }");
    }

    private static string PropertyType(QuestionModel question) => question.Kind switch
    {
        QuestionKind.Noul => "global::Minos.Noul",
        QuestionKind.Choice => "global::Minos.Choice<" + question.EnumType + ">",
        _ => "global::Minos.Score<" + question.EnumType + ">",
    };

    private static string Field(QuestionModel question) => "__minos_" + question.PropertyName.TrimStart('@');

    private static string OptionSet(QuestionModel question) => "__DecisionOptions_" + question.PropertyName.TrimStart('@');

    private static string Int(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>Appends lines with <c>\n</c> endings so the output does not depend on the build machine.</summary>
    private sealed class CodeWriter
    {
        private readonly StringBuilder _text = new();

        public void Line(string text = "") => _text.Append(text).Append('\n');

        public override string ToString() => _text.ToString();
    }
}
