<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\benchmarks\ZeroAlloc.Jev.Benchmarks.Mock\ZeroAlloc.Jev.Benchmarks.Mock.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\benchmarks\compare\workload\response.json" Link="response.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
