//HintName: Demo.DepartmentRouting.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record DepartmentRouting : global::Jev.Net.IJevQuestionSet<global::Demo.DepartmentRouting>
{
    private global::Jev.Net.Choice<global::Demo.Department> __jev_Department;

    public partial global::Jev.Net.Choice<global::Demo.Department> Department { get => __jev_Department; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"department\":{\"type\":\"choice\",\"instructions\":\"Which team should handle this?\",\"criteria\":{\"billing\":\"Payments, invoicing, refunds\",\"tech\":\"Bugs, outages, integrations\",\"other\":null}}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.DepartmentRouting Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Jev.Net.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[3];
        var result = new global::Demo.DepartmentRouting();
        var found0 = false;
        while (global::Jev.Net.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("department"u8))
            {
                answers.Read();
                result.__jev_Department = global::Jev.Net.JevAnswerReader.ReadChoice(ref answers, __JevOptions_Department.Instance, buffer, 0);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Jev.Net.JevAnswerReader.MissingAnswer("department");
        return result;
    }

    private sealed class __JevOptions_Department : global::Jev.Net.JevOptionSet<global::Demo.Department>
    {
        public static readonly __JevOptions_Department Instance = new();

        public override int Count => 3;

        public override global::Demo.Department this[int index] => index switch
        {
            0 => global::Demo.Department.Billing,
            1 => global::Demo.Department.Technical,
            2 => global::Demo.Department.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Department value) => value switch
        {
            global::Demo.Department.Billing => 0,
            global::Demo.Department.Technical => 1,
            global::Demo.Department.Other => 2,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("billing"u8)) return 0;
            if (reader.ValueTextEquals("tech"u8)) return 1;
            if (reader.ValueTextEquals("other"u8)) return 2;
            return -1;
        }
    }
}
