//HintName: Demo.StructuredRouting.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record StructuredRouting : global::Minos.IQuestionSet<global::Demo.StructuredRouting>
{
    private global::Minos.Choice<global::Demo.StructuredDepartment> __minos_Department;
    private global::Minos.Score<global::Demo.StructuredSeverity> __minos_Severity;

    public partial global::Minos.Choice<global::Demo.StructuredDepartment> Department { get => __minos_Department; }
    public partial global::Minos.Score<global::Demo.StructuredSeverity> Severity { get => __minos_Severity; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"department\":{\"type\":\"choice\",\"instructions\":\"Which team should handle this?\",\"criteria\":{\"billing\":{\"description\":\"Payments, invoicing, refunds\",\"examples\":[\"I was charged twice\"],\"not_for\":[\"How much is Pro?\"]},\"technical\":{\"description\":\"Bugs, outages, integrations\",\"examples\":[\"The API returns 500\"]},\"sales\":\"Pricing, upgrades, new accounts\",\"other\":null}},\"severity\":{\"type\":\"score\",\"instructions\":\"How severe is this?\",\"criteria\":[{\"description\":\"Cosmetic\",\"not_for\":[\"Data loss\"]},\"Blocks work\"]}}"u8;

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Choice(
            "department",
            global::Minos.DecisionContent.FromString("Which team should handle this?"),
            new global::Minos.OptionDefinition("billing", global::Minos.Criterion.Text("Payments, invoicing, refunds").WithExamples("I was charged twice").WithNotFor("How much is Pro?")),
            new global::Minos.OptionDefinition("technical", global::Minos.Criterion.Text("Bugs, outages, integrations").WithExamples("The API returns 500")),
            new global::Minos.OptionDefinition("sales", global::Minos.Criterion.Text("Pricing, upgrades, new accounts")),
            new global::Minos.OptionDefinition("other", null)),
        global::Minos.QuestionDefinition.Score(
            "severity",
            global::Minos.DecisionContent.FromString("How severe is this?"),
            global::Minos.Criterion.Text("Cosmetic").WithNotFor("Data loss"),
            global::Minos.Criterion.Text("Blocks work")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.StructuredRouting Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.StructuredRouting();
        result.__minos_Department = answers.Choice(0, __DecisionOptions_Department.Instance);
        result.__minos_Severity = answers.Score(1, __DecisionOptions_Severity.Instance);
        return result;
    }

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.StructuredRouting Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Minos.AnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[6];
        var result = new global::Demo.StructuredRouting();
        var found0 = false;
        var found1 = false;
        while (global::Minos.AnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("department"u8))
            {
                answers.Read();
                result.__minos_Department = global::Minos.AnswerReader.ReadChoice(ref answers, __DecisionOptions_Department.Instance, buffer, 0);
                found0 = true;
            }
            else if (answers.ValueTextEquals("severity"u8))
            {
                answers.Read();
                result.__minos_Severity = global::Minos.AnswerReader.ReadScore(ref answers, __DecisionOptions_Severity.Instance, buffer, 4);
                found1 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Minos.AnswerReader.MissingAnswer("department");
        if (!found1) throw global::Minos.AnswerReader.MissingAnswer("severity");
        return result;
    }

    private sealed class __DecisionOptions_Department : global::Minos.DecisionOptionSet<global::Demo.StructuredDepartment>
    {
        public static readonly __DecisionOptions_Department Instance = new();

        public override int Count => 4;

        public override global::Demo.StructuredDepartment this[int index] => index switch
        {
            0 => global::Demo.StructuredDepartment.Billing,
            1 => global::Demo.StructuredDepartment.Technical,
            2 => global::Demo.StructuredDepartment.Sales,
            3 => global::Demo.StructuredDepartment.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredDepartment value) => value switch
        {
            global::Demo.StructuredDepartment.Billing => 0,
            global::Demo.StructuredDepartment.Technical => 1,
            global::Demo.StructuredDepartment.Sales => 2,
            global::Demo.StructuredDepartment.Other => 3,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("billing"u8)) return 0;
            if (reader.ValueTextEquals("technical"u8)) return 1;
            if (reader.ValueTextEquals("sales"u8)) return 2;
            if (reader.ValueTextEquals("other"u8)) return 3;
            return -1;
        }
    }

    private sealed class __DecisionOptions_Severity : global::Minos.DecisionOptionSet<global::Demo.StructuredSeverity>
    {
        public static readonly __DecisionOptions_Severity Instance = new();

        public override int Count => 2;

        public override global::Demo.StructuredSeverity this[int index] => index switch
        {
            0 => global::Demo.StructuredSeverity.Low,
            1 => global::Demo.StructuredSeverity.High,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredSeverity value) => value switch
        {
            global::Demo.StructuredSeverity.Low => 0,
            global::Demo.StructuredSeverity.High => 1,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("0"u8)) return 0;
            if (reader.ValueTextEquals("1"u8)) return 1;
            return -1;
        }
    }
}
