//HintName: Demo.StructuredRouting.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record StructuredRouting : global::Minos.IQuestionSet<global::Demo.StructuredRouting>
{
    private global::Minos.Choice<global::Demo.StructuredDepartment> __minos_Department;
    private global::Minos.Score<global::Demo.StructuredSeverity> __minos_Severity;

    public partial global::Minos.Choice<global::Demo.StructuredDepartment> Department { get => __minos_Department; }
    public partial global::Minos.Score<global::Demo.StructuredSeverity> Severity { get => __minos_Severity; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Choice(
            "department",
            global::Minos.DecisionContent.FromString("Which team should handle this?"),
            new global::Minos.OptionDefinition("billing", global::Minos.Criterion.Text("Payments, invoicing, refunds").WithExamples("I was charged twice").WithNotFor("How much is Pro?")),
            new global::Minos.OptionDefinition("technical", global::Minos.Criterion.Text("Bugs, outages, integrations").WithExamples("The API returns 500")),
            new global::Minos.OptionDefinition("sales", global::Minos.Criterion.Text("Pricing, upgrades, new accounts")),
            new global::Minos.OptionDefinition("other", null)),
        global::Minos.QuestionDefinition.Score(
            "severity",
            global::Minos.DecisionContent.FromString("How severe is this?"),
            global::Minos.Criterion.Text("Cosmetic").WithNotFor("Data loss"),
            global::Minos.Criterion.Text("Blocks work")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.StructuredRouting Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.StructuredRouting();
        result.__minos_Department = answers.Choice(0, __DecisionOptions_Department.Instance);
        result.__minos_Severity = answers.Score(1, __DecisionOptions_Severity.Instance);
        return result;
    }

    private sealed class __DecisionOptions_Department : global::Minos.DecisionOptionSet<global::Demo.StructuredDepartment>
    {
        public static readonly __DecisionOptions_Department Instance = new();

        public override int Count => 4;

        public override global::Demo.StructuredDepartment this[int index] => index switch
        {
            0 => global::Demo.StructuredDepartment.Billing,
            1 => global::Demo.StructuredDepartment.Technical,
            2 => global::Demo.StructuredDepartment.Sales,
            3 => global::Demo.StructuredDepartment.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredDepartment value) => value switch
        {
            global::Demo.StructuredDepartment.Billing => 0,
            global::Demo.StructuredDepartment.Technical => 1,
            global::Demo.StructuredDepartment.Sales => 2,
            global::Demo.StructuredDepartment.Other => 3,
            _ => -1,
        };
    }

    private sealed class __DecisionOptions_Severity : global::Minos.DecisionOptionSet<global::Demo.StructuredSeverity>
    {
        public static readonly __DecisionOptions_Severity Instance = new();

        public override int Count => 2;

        public override global::Demo.StructuredSeverity this[int index] => index switch
        {
            0 => global::Demo.StructuredSeverity.Low,
            1 => global::Demo.StructuredSeverity.High,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.StructuredSeverity value) => value switch
        {
            global::Demo.StructuredSeverity.Low => 0,
            global::Demo.StructuredSeverity.High => 1,
            _ => -1,
        };
    }
}
