//HintName: Demo.AbstractStateSet.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record AbstractStateSet : global::Minos.IQuestionSet<global::Demo.AbstractStateSet, global::Demo.StateBase>
{
    private global::Minos.Noul __minos_Answer;

    public partial global::Minos.Noul Answer { get => __minos_Answer; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Noul(
            "answer",
            global::Minos.DecisionContent.FromString("q")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.AbstractStateSet Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.AbstractStateSet();
        result.__minos_Answer = answers.Noul(0);
        return result;
    }
}
