//HintName: Demo.UrgencyCheck.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record UrgencyCheck : global::Minos.IJevQuestionSet<global::Demo.UrgencyCheck>
{
    private global::Minos.Noul __jev_IsUrgent;

    public partial global::Minos.Noul IsUrgent { get => __jev_IsUrgent; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"is_urgent\":{\"type\":\"noul\",\"instructions\":\"Does this convey urgency?\",\"criteria\":{\"true\":\"Explicitly time-sensitive\",\"false\":\"No urgency expressed\"}}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.UrgencyCheck Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Minos.JevAnswerReader.EnsureStartObject(ref answers);
        var result = new global::Demo.UrgencyCheck();
        var found0 = false;
        while (global::Minos.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("is_urgent"u8))
            {
                answers.Read();
                result.__jev_IsUrgent = global::Minos.JevAnswerReader.ReadNoul(ref answers);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Minos.JevAnswerReader.MissingAnswer("is_urgent");
        return result;
    }
}
