//HintName: class.event.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace @class;

partial record @event : global::Minos.IQuestionSet<global::@class.@event>
{
    private global::Minos.Noul __minos_Answer;

    public partial global::Minos.Noul Answer { get => __minos_Answer; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"answer\":{\"type\":\"noul\",\"instructions\":\"q\"}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::@class.@event Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Minos.AnswerReader.EnsureStartObject(ref answers);
        var result = new global::@class.@event();
        var found0 = false;
        while (global::Minos.AnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("answer"u8))
            {
                answers.Read();
                result.__minos_Answer = global::Minos.AnswerReader.ReadNoul(ref answers);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Minos.AnswerReader.MissingAnswer("answer");
        return result;
    }
}
