//HintName: TicketTriage.Questions.g.cs
// <auto-generated/>
#nullable enable

partial class TicketTriage : global::Minos.IQuestionSet<global::TicketTriage>
{
    private global::Minos.Noul __minos_RequestsCredentials;
    private global::Minos.Choice<global::Team> __minos_Team;
    private global::Minos.Score<global::Urgency> __minos_Urgency;

    public partial global::Minos.Noul RequestsCredentials { get => __minos_RequestsCredentials; }
    public partial global::Minos.Choice<global::Team> Team { get => __minos_Team; }
    internal partial global::Minos.Score<global::Urgency> Urgency { get => __minos_Urgency; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Noul(
            "requests_credentials",
            global::Minos.DecisionContent.FromString("Does `message` ask for a \"credential\"?"),
            whenFalse: global::Minos.DecisionContent.FromString("No credential is requested")),
        global::Minos.QuestionDefinition.Choice(
            "route_to",
            global::Minos.DecisionContent.FromString("Which team should handle `message`?"),
            new global::Minos.OptionDefinition("billing", global::Minos.Criterion.Text("Charges, invoices, refunds")),
            new global::Minos.OptionDefinition("account", global::Minos.Criterion.Text("Login, profile, permissions, or security")),
            new global::Minos.OptionDefinition("other", global::Minos.Criterion.Text("No listed team fits"))),
        global::Minos.QuestionDefinition.Score(
            "urgency",
            global::Minos.DecisionContent.FromString("How urgent is `message`?"),
            global::Minos.Criterion.Text("Can wait"),
            global::Minos.Criterion.Text("This week"),
            global::Minos.Criterion.Text("Today")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::TicketTriage Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::TicketTriage();
        result.__minos_RequestsCredentials = answers.Noul(0);
        result.__minos_Team = answers.Choice(1, __DecisionOptions_Team.Instance);
        result.__minos_Urgency = answers.Score(2, __DecisionOptions_Urgency.Instance);
        return result;
    }

    private sealed class __DecisionOptions_Team : global::Minos.DecisionOptionSet<global::Team>
    {
        public static readonly __DecisionOptions_Team Instance = new();

        public override int Count => 3;

        public override global::Team this[int index] => index switch
        {
            0 => global::Team.Billing,
            1 => global::Team.Account,
            2 => global::Team.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Team value) => value switch
        {
            global::Team.Billing => 0,
            global::Team.Account => 1,
            global::Team.Other => 2,
            _ => -1,
        };
    }

    private sealed class __DecisionOptions_Urgency : global::Minos.DecisionOptionSet<global::Urgency>
    {
        public static readonly __DecisionOptions_Urgency Instance = new();

        public override int Count => 3;

        public override global::Urgency this[int index] => index switch
        {
            0 => global::Urgency.Low,
            1 => global::Urgency.Medium,
            2 => global::Urgency.High,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Urgency value) => value switch
        {
            global::Urgency.Low => 0,
            global::Urgency.Medium => 1,
            global::Urgency.High => 2,
            _ => -1,
        };
    }
}
