//HintName: Demo.FrustrationCheck.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record FrustrationCheck : global::Minos.IQuestionSet<global::Demo.FrustrationCheck>
{
    private global::Minos.Score<global::Demo.Frustration> __minos_Frustration;

    public partial global::Minos.Score<global::Demo.Frustration> Frustration { get => __minos_Frustration; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Score(
            "frustration",
            global::Minos.DecisionContent.FromString("How frustrated is the customer?"),
            global::Minos.Criterion.Text("Calm"),
            global::Minos.Criterion.Text("Frustrated"),
            global::Minos.Criterion.Text("Very angry")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.FrustrationCheck Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.FrustrationCheck();
        result.__minos_Frustration = answers.Score(0, __DecisionOptions_Frustration.Instance);
        return result;
    }

    private sealed class __DecisionOptions_Frustration : global::Minos.DecisionOptionSet<global::Demo.Frustration>
    {
        public static readonly __DecisionOptions_Frustration Instance = new();

        public override int Count => 3;

        public override global::Demo.Frustration this[int index] => index switch
        {
            0 => global::Demo.Frustration.Calm,
            1 => global::Demo.Frustration.Frustrated,
            2 => global::Demo.Frustration.VeryAngry,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Frustration value) => value switch
        {
            global::Demo.Frustration.Calm => 0,
            global::Demo.Frustration.Frustrated => 1,
            global::Demo.Frustration.VeryAngry => 2,
            _ => -1,
        };
    }
}
