//HintName: Demo.KeywordMemberCheck.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record KeywordMemberCheck : global::Minos.IJevQuestionSet<global::Demo.KeywordMemberCheck>
{
    private global::Minos.Choice<global::Demo.Verdict> __jev_class;

    public partial global::Minos.Choice<global::Demo.Verdict> @class { get => __jev_class; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"class\":{\"type\":\"choice\",\"instructions\":\"What is the verdict?\",\"criteria\":{\"approved\":\"Approved\",\"for\":\"Denied\"}}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.KeywordMemberCheck Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Minos.JevAnswerReader.EnsureStartObject(ref answers);
        var buffer = new double[2];
        var result = new global::Demo.KeywordMemberCheck();
        var found0 = false;
        while (global::Minos.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("class"u8))
            {
                answers.Read();
                result.__jev_class = global::Minos.JevAnswerReader.ReadChoice(ref answers, __JevOptions_class.Instance, buffer, 0);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Minos.JevAnswerReader.MissingAnswer("class");
        return result;
    }

    private sealed class __JevOptions_class : global::Minos.JevOptionSet<global::Demo.Verdict>
    {
        public static readonly __JevOptions_class Instance = new();

        public override int Count => 2;

        public override global::Demo.Verdict this[int index] => index switch
        {
            0 => global::Demo.Verdict.Approved,
            1 => global::Demo.Verdict.@for,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Verdict value) => value switch
        {
            global::Demo.Verdict.Approved => 0,
            global::Demo.Verdict.@for => 1,
            _ => -1,
        };

        public override int IndexOfKey(ref global::System.Text.Json.Utf8JsonReader reader)
        {
            if (reader.ValueTextEquals("approved"u8)) return 0;
            if (reader.ValueTextEquals("for"u8)) return 1;
            return -1;
        }
    }
}
