//HintName: Demo.Set.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record Set : global::Minos.IQuestionSet<global::Demo.Set, global::Demo.TicketContext>
{
    private global::Minos.Noul __minos_IsUrgent;

    public partial global::Minos.Noul IsUrgent { get => __minos_IsUrgent; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Noul(
            "is_urgent",
            global::Minos.DecisionContent.FromString("Is this urgent?")));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.Set Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.Set();
        result.__minos_IsUrgent = answers.Noul(0);
        return result;
    }
}
