//HintName: Demo.ArrayStateSet.JevQuestions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record ArrayStateSet : global::Minos.IJevQuestionSet<global::Demo.ArrayStateSet, global::Demo.ChatMessage[]>
{
    private global::Minos.Noul __jev_Answer;

    public partial global::Minos.Noul Answer { get => __jev_Answer; }

    /// <summary>Gets the <c>questions</c> object of a <c>/v1/systemone</c> request, as UTF-8 JSON.</summary>
    public static global::System.ReadOnlySpan<byte> QuestionsUtf8 => "{\"answer\":{\"type\":\"noul\",\"instructions\":\"q\"}}"u8;

    /// <summary>Reads the typed answers from the <c>answers</c> object of a <c>/v1/systemone</c> response.</summary>
    /// <param name="answers">A reader over complete JSON, positioned on the start of the <c>answers</c> object. It is left on the object's end.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.ArrayStateSet Parse(ref global::System.Text.Json.Utf8JsonReader answers)
    {
        global::Minos.JevAnswerReader.EnsureStartObject(ref answers);
        var result = new global::Demo.ArrayStateSet();
        var found0 = false;
        while (global::Minos.JevAnswerReader.NextProperty(ref answers))
        {
            if (answers.ValueTextEquals("answer"u8))
            {
                answers.Read();
                result.__jev_Answer = global::Minos.JevAnswerReader.ReadNoul(ref answers);
                found0 = true;
            }
            else
            {
                answers.Skip();
            }
        }
        if (!found0) throw global::Minos.JevAnswerReader.MissingAnswer("answer");
        return result;
    }
}
