//HintName: Demo.DepartmentRouting.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record DepartmentRouting : global::Minos.IQuestionSet<global::Demo.DepartmentRouting>
{
    private global::Minos.Choice<global::Demo.Department> __minos_Department;

    public partial global::Minos.Choice<global::Demo.Department> Department { get => __minos_Department; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Choice(
            "department",
            global::Minos.DecisionContent.FromString("Which team should handle this?"),
            new global::Minos.OptionDefinition("billing", global::Minos.Criterion.Text("Payments, invoicing, refunds")),
            new global::Minos.OptionDefinition("tech", global::Minos.Criterion.Text("Bugs, outages, integrations")),
            new global::Minos.OptionDefinition("other", null)));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.DepartmentRouting Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.DepartmentRouting();
        result.__minos_Department = answers.Choice(0, __DecisionOptions_Department.Instance);
        return result;
    }

    private sealed class __DecisionOptions_Department : global::Minos.DecisionOptionSet<global::Demo.Department>
    {
        public static readonly __DecisionOptions_Department Instance = new();

        public override int Count => 3;

        public override global::Demo.Department this[int index] => index switch
        {
            0 => global::Demo.Department.Billing,
            1 => global::Demo.Department.Technical,
            2 => global::Demo.Department.Other,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Department value) => value switch
        {
            global::Demo.Department.Billing => 0,
            global::Demo.Department.Technical => 1,
            global::Demo.Department.Other => 2,
            _ => -1,
        };
    }
}
