//HintName: Demo.KeywordMemberCheck.Questions.g.cs
// <auto-generated/>
#nullable enable

namespace Demo;

partial record KeywordMemberCheck : global::Minos.IQuestionSet<global::Demo.KeywordMemberCheck>
{
    private global::Minos.Choice<global::Demo.Verdict> __minos_class;

    public partial global::Minos.Choice<global::Demo.Verdict> @class { get => __minos_class; }

    /// <summary>Gets the provider-neutral definition of the set's questions.</summary>
    public static global::Minos.QuestionSetDefinition Definition { get; } = new global::Minos.QuestionSetDefinition(
        global::Minos.QuestionDefinition.Choice(
            "class",
            global::Minos.DecisionContent.FromString("What is the verdict?"),
            new global::Minos.OptionDefinition("approved", global::Minos.Criterion.Text("Approved")),
            new global::Minos.OptionDefinition("for", global::Minos.Criterion.Text("Denied"))));

    /// <summary>Creates the typed answers from the slots a protocol read for <see cref="Definition"/>.</summary>
    /// <param name="answers">One slot per question, in <see cref="Definition"/> order.</param>
    /// <returns>The typed answers.</returns>
    public static global::Demo.KeywordMemberCheck Create(global::Minos.AnswerSlots answers)
    {
        var result = new global::Demo.KeywordMemberCheck();
        result.__minos_class = answers.Choice(0, __DecisionOptions_class.Instance);
        return result;
    }

    private sealed class __DecisionOptions_class : global::Minos.DecisionOptionSet<global::Demo.Verdict>
    {
        public static readonly __DecisionOptions_class Instance = new();

        public override int Count => 2;

        public override global::Demo.Verdict this[int index] => index switch
        {
            0 => global::Demo.Verdict.Approved,
            1 => global::Demo.Verdict.@for,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(index)),
        };

        public override int IndexOf(global::Demo.Verdict value) => value switch
        {
            global::Demo.Verdict.Approved => 0,
            global::Demo.Verdict.@for => 1,
            _ => -1,
        };
    }
}
